on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy portfolio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Setup .env and secrets
        run: |
          touch .env
          echo NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }} >> .env
          echo NEXT_PUBLIC_SANITY_DATASET=production >> .env
          echo NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }} >> .env.local
          echo NEXT_PUBLIC_SANITY_DATASET=production >> .env.local
          cat .env

      - name: npm install, npm build
        run: |
          npm ci
          npm run build --if-exists

      - name: Copy static files
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./.next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: "Deploy to Azure"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "portfolio-dewaldels"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "."
